spring.application.name=gateway
server.port=9090

# Enable service discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.config.import=configserver:http://localhost:8080
spring.profiles.active=dev
management.endpoints.web.exposure.include=refresh