spring.application.name=configserver

spring.cloud.config.server.git.uri=https://github.com/Nitin-Pilkhwal-TTN/demo-micro-service-config
spring.cloud.config.server.git.clone-on-start=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true